Repository Nuri-Capstone/backend, pull requests merged in 2024-12, with the labels that each got.

#18 [feat] 채팅방 GPT Feedback 호출, 응답 기능
  src/main/java/com/nuri/nuribackend/controller/SocketVoiceHandler.java
  src/main/java/com/nuri/nuribackend/domain/Feedback/Feedback.java
  src/main/java/com/nuri/nuribackend/domain/Feedback/FeedbackContent.java
  src/main/java/com/nuri/nuribackend/dto/GPT/FeedbackMessage.java
  src/main/java/com/nuri/nuribackend/service/GPTService.java
Labels: :kiwi_fruit: feature

#20 [refactor] 월별 피드백 로직 제거
  src/main/java/com/nuri/nuribackend/controller/HomeController.java
  src/main/java/com/nuri/nuribackend/domain/Feedback/Feedback.java
  src/main/java/com/nuri/nuribackend/domain/Feedback/MonthlyFeedback.java
  src/main/java/com/nuri/nuribackend/dto/Feedback/MonthlyFeedbackFromGPT.java
  src/main/java/com/nuri/nuribackend/repository/MonthlyFeedbackRepository.java
  src/main/java/com/nuri/nuribackend/repository/UserRepository.java
  src/main/java/com/nuri/nuribackend/service/SampleService.java
  src/main/java/com/nuri/nuribackend/service/home/MonthlyFeedbackService.java
Labels: 🛠 fix, 💻 refactor

#26 [refact] feedback 데이터 저장 속성 변경
  src/main/java/com/nuri/nuribackend/controller/SocketVoiceHandler.java
  src/main/java/com/nuri/nuribackend/service/GPTService.java
Labels: 📀 database, 💻 refactor

#28 [feat] 채팅 리스트 불러오기 기능
  src/main/java/com/nuri/nuribackend/controller/ChatListController.java
  src/main/java/com/nuri/nuribackend/controller/SocketVoiceHandler.java
  src/main/java/com/nuri/nuribackend/domain/Chat.java
  src/main/java/com/nuri/nuribackend/domain/User.java
  src/main/java/com/nuri/nuribackend/dto/Chat/ChatDto.java
  src/main/java/com/nuri/nuribackend/repository/ChatRepository.java
  src/main/java/com/nuri/nuribackend/service/ChatListService.java
Labels: :kiwi_fruit: feature

#32 [FEAT] 채팅방 summary 구현
  src/main/java/com/nuri/nuribackend/repository/ChatMessageRepository.java
  src/main/java/com/nuri/nuribackend/repository/ChatRepository.java
  src/main/java/com/nuri/nuribackend/service/ChatSummaryService.java
  src/main/java/com/nuri/nuribackend/service/home/OpenAiService.java
Labels: :kiwi_fruit: feature

#33 [feat] 채팅방 내용 불러오기 기능
  src/main/java/com/nuri/nuribackend/controller/ChatMessageController.java
  src/main/java/com/nuri/nuribackend/dto/ChatMessageDto.java
  src/main/java/com/nuri/nuribackend/repository/ChatMessageRepository.java
  src/main/java/com/nuri/nuribackend/service/ChatMessageService.java
Labels: :kiwi_fruit: feature

#34 [feat] 로그인, 회원가입 인가
  build.gradle
  src/main/java/com/nuri/nuribackend/config/SecurityConfig.java
  src/main/java/com/nuri/nuribackend/config/WebSocketConfig.java
  src/main/java/com/nuri/nuribackend/controller/GlobalExceptionHandler.java
  src/main/java/com/nuri/nuribackend/controller/HomeController.java
  src/main/java/com/nuri/nuribackend/controller/JwtTokenProvider.java
  src/main/java/com/nuri/nuribackend/controller/SocketVoiceHandler.java
  src/main/java/com/nuri/nuribackend/controller/UserController.java
  src/main/java/com/nuri/nuribackend/domain/Chat.java
  src/main/java/com/nuri/nuribackend/domain/Ranking.java
  src/main/java/com/nuri/nuribackend/domain/User.java
  src/main/java/com/nuri/nuribackend/dto/ChatDto.java
  src/main/java/com/nuri/nuribackend/dto/Error/ErrorResponse.java
  src/main/java/com/nuri/nuribackend/dto/Feedback/RankingDto.java
  src/main/java/com/nuri/nuribackend/dto/User/JwtTokenDto.java
  src/main/java/com/nuri/nuribackend/dto/User/SignInDto.java
  src/main/java/com/nuri/nuribackend/dto/User/SignUpDto.java
  src/main/java/com/nuri/nuribackend/dto/User/UserDto.java
  src/main/java/com/nuri/nuribackend/dto/User/UserGetRequest.java
  src/main/java/com/nuri/nuribackend/dto/User/UserGetResponse.java
  src/main/java/com/nuri/nuribackend/dto/User/UserPostRequest.java
  src/main/java/com/nuri/nuribackend/dto/User/UserPostResponse.java
  src/main/java/com/nuri/nuribackend/dto/UserDto.java
  src/main/java/com/nuri/nuribackend/exception/AuthenticationException.java
  src/main/java/com/nuri/nuribackend/exception/AuthorizationException.java
  src/main/java/com/nuri/nuribackend/exception/CustomException.java
  src/main/java/com/nuri/nuribackend/repository/RankingRepository.java
  src/main/java/com/nuri/nuribackend/repository/UserRepository.java
  src/main/java/com/nuri/nuribackend/service/ChatService.java
  src/main/java/com/nuri/nuribackend/service/CustomUserDetailsService.java
  src/main/java/com/nuri/nuribackend/service/RankingService.java
  src/main/java/com/nuri/nuribackend/service/S3Service.java
  src/main/java/com/nuri/nuribackend/service/SampleService.java
  src/main/java/com/nuri/nuribackend/service/UserService.java
  src/main/java/com/nuri/nuribackend/utils/AuthHandshakeInterceptor.java
  src/main/java/com/nuri/nuribackend/utils/JwtAuthenticationFilter.java
Labels: :kiwi_fruit: feature

#36 [refact]채팅방 생성 수정
  src/main/java/com/nuri/nuribackend/controller/SocketVoiceHandler.java
Labels: 💻 refactor

#38 [refactor] summary 수정
  src/main/java/com/nuri/nuribackend/controller/ChatMessageController.java
  src/main/java/com/nuri/nuribackend/controller/SocketVoiceHandler.java
Labels: 💻 refactor

#40 feat: ✨ 사용자 순위 기능 추가
  src/main/java/com/nuri/nuribackend/controller/HomeController.java
  src/main/java/com/nuri/nuribackend/repository/RankingRepository.java
  src/main/java/com/nuri/nuribackend/service/RankingService.java
Labels: :kiwi_fruit: feature

#42 feat: ✨ 랭킹 데이터 추출
  src/main/java/com/nuri/nuribackend/controller/HomeController.java
  src/main/java/com/nuri/nuribackend/domain/User.java
  src/main/java/com/nuri/nuribackend/repository/RankingRepository.java
  src/main/java/com/nuri/nuribackend/service/RankingService.java
Labels: :kiwi_fruit: feature

#44 [feat] 기능 통합
  src/main/java/com/nuri/nuribackend/SampleInitializer.java
  src/main/java/com/nuri/nuribackend/controller/ChatMessageController.java
  src/main/java/com/nuri/nuribackend/service/GPTService.java
Labels: :kiwi_fruit: feature

#48 [FEAT] ✨ 홈피드 토큰 적용
  src/main/java/com/nuri/nuribackend/controller/HomeController.java
  src/main/java/com/nuri/nuribackend/service/GPTService.java
  src/main/java/com/nuri/nuribackend/service/home/OpenAiService.java
Labels: :kiwi_fruit: feature
